/* Generated by Yosys 0.23 (git sha1 7ce5011c24b) */
`include "alm_sim.v"
`include "misc_sim.v"

(* top =  1  *)
(* src = "./mxalu11u.v:27.1-73.10" *)
module mxalu11u_intel(f, x, y, a_b, cn4_n, cn8_n, opcode, a, b, cs_n);
  (* src = "./mxalu11u.v:35.15-35.16" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "./mxalu11u.v:31.15-31.18" *)
  output a_b;
  wire a_b;
  (* src = "./mxalu11u.v:36.15-36.16" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "./mxalu11u.v:32.15-32.20" *)
  output cn4_n;
  wire cn4_n;
  (* src = "./mxalu11u.v:33.15-33.20" *)
  output cn8_n;
  wire cn8_n;
  (* src = "./mxalu11u.v:37.15-37.19" *)
  input cs_n;
  wire cs_n;
  (* src = "./mxalu11u.v:28.15-28.16" *)
  output [7:0] f;
  wire [7:0] f;
  (* hdlname = "inst_mxalu181_rom cs_n" *)
  (* src = "./mxalu11u.v:43.15-49.3|./mxalu_rom.v:69.19-69.23" *)
  (* unused_bits = "0" *)
  wire \inst_mxalu181_rom.cs_n ;
  (* hdlname = "inst_mxalu181_rom opcode" *)
  (* src = "./mxalu11u.v:43.15-49.3|./mxalu_rom.v:68.19-68.25" *)
  wire [3:0] \inst_mxalu181_rom.opcode ;
  (* hdlname = "inst_mxalu_181 a_b" *)
  (* src = "./mxalu11u.v:51.12-63.3|./mxalu_181.v:5.15-5.18" *)
  wire \inst_mxalu_181.a_b ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [4:0] \inst_mxalu_181.a_b_MISTRAL_ALUT5_Q_E ;
  (* hdlname = "inst_mxalu_181 cn4_n" *)
  (* src = "./mxalu11u.v:51.12-63.3|./mxalu_181.v:6.15-6.20" *)
  wire \inst_mxalu_181.cn4_n ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [1:0] \inst_mxalu_181.cn4_n_MISTRAL_ALUT6_F_Q ;
  (* hdlname = "inst_mxalu_181 cn8_n" *)
  (* src = "./mxalu11u.v:51.12-63.3|./mxalu_181.v:7.15-7.20" *)
  wire \inst_mxalu_181.cn8_n ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [2:0] \inst_mxalu_181.cn8_n_MISTRAL_ALUT3_Q_A ;
  (* hdlname = "inst_mxalu_181 f" *)
  (* src = "./mxalu11u.v:51.12-63.3|./mxalu_181.v:2.15-2.16" *)
  wire [7:0] \inst_mxalu_181.f ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [1:0] \inst_mxalu_181.f_MISTRAL_ALUT2_Q_1_B ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [3:0] \inst_mxalu_181.f_MISTRAL_ALUT4_Q_B ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [4:0] \inst_mxalu_181.f_MISTRAL_ALUT4_Q_C ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [4:0] \inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [5:0] \inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_B ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [5:0] \inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_C ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [5:0] \inst_mxalu_181.f_MISTRAL_ALUT6_Q_C ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [5:0] \inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E ;
  (* hdlname = "inst_mxalu_181 inst_alu0 inst_s520 a" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:55.15-60.3|./74181.v:135.15-135.16|./mxalu_181.v:18.9-29.3" *)
  wire \inst_mxalu_181.inst_alu0.inst_s520.a ;
  (* hdlname = "inst_mxalu_181 inst_alu0 inst_s520 b" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:55.15-60.3|./74181.v:136.15-136.16|./mxalu_181.v:18.9-29.3" *)
  wire \inst_mxalu_181.inst_alu0.inst_s520.b ;
  (* hdlname = "inst_mxalu_181 inst_alu0 inst_s520 inst_s21 dt" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:55.15-60.3|./74181.v:120.15-120.17|./74181.v:138.15-141.3|./mxalu_181.v:18.9-29.3" *)
  (* unused_bits = "0 1 3" *)
  wire [4:0] \inst_mxalu_181.inst_alu0.inst_s520.inst_s21.dt ;
  (* hdlname = "inst_mxalu_181 inst_alu0 inst_s521 a" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:62.15-67.3|./74181.v:135.15-135.16|./mxalu_181.v:18.9-29.3" *)
  wire \inst_mxalu_181.inst_alu0.inst_s521.a ;
  (* hdlname = "inst_mxalu_181 inst_alu0 inst_s521 b" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:62.15-67.3|./74181.v:136.15-136.16|./mxalu_181.v:18.9-29.3" *)
  wire \inst_mxalu_181.inst_alu0.inst_s521.b ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [1:0] \inst_mxalu_181.inst_alu0.inst_s521.b_MISTRAL_ALUT5_A_Q ;
  (* hdlname = "inst_mxalu_181 inst_alu0 inst_s521 inst_s21 dt" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:62.15-67.3|./74181.v:120.15-120.17|./74181.v:138.15-141.3|./mxalu_181.v:18.9-29.3" *)
  (* unused_bits = "0 1 3" *)
  wire [4:0] \inst_mxalu_181.inst_alu0.inst_s521.inst_s21.dt ;
  (* hdlname = "inst_mxalu_181 inst_alu0 inst_s522 a" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:69.15-74.3|./74181.v:135.15-135.16|./mxalu_181.v:18.9-29.3" *)
  wire \inst_mxalu_181.inst_alu0.inst_s522.a ;
  (* hdlname = "inst_mxalu_181 inst_alu0 inst_s522 b" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:69.15-74.3|./74181.v:136.15-136.16|./mxalu_181.v:18.9-29.3" *)
  wire \inst_mxalu_181.inst_alu0.inst_s522.b ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [4:0] \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT4_A_Q ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [5:0] \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [5:0] \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q ;
  (* hdlname = "inst_mxalu_181 inst_alu0 inst_s522 inst_s21 dt" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:69.15-74.3|./74181.v:120.15-120.17|./74181.v:138.15-141.3|./mxalu_181.v:18.9-29.3" *)
  (* unused_bits = "0 1 3" *)
  wire [4:0] \inst_mxalu_181.inst_alu0.inst_s522.inst_s21.dt ;
  (* hdlname = "inst_mxalu_181 inst_alu0 inst_s523 a" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:76.15-81.3|./74181.v:135.15-135.16|./mxalu_181.v:18.9-29.3" *)
  wire \inst_mxalu_181.inst_alu0.inst_s523.a ;
  (* hdlname = "inst_mxalu_181 inst_alu0 inst_s523 b" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:76.15-81.3|./74181.v:136.15-136.16|./mxalu_181.v:18.9-29.3" *)
  wire \inst_mxalu_181.inst_alu0.inst_s523.b ;
  (* hdlname = "inst_mxalu_181 inst_alu0 inst_s523 inst_s21 dt" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:76.15-81.3|./74181.v:120.15-120.17|./74181.v:138.15-141.3|./mxalu_181.v:18.9-29.3" *)
  (* unused_bits = "0 1 3" *)
  wire [4:0] \inst_mxalu_181.inst_alu0.inst_s523.inst_s21.dt ;
  (* hdlname = "inst_mxalu_181 inst_alu1 inst_s520 a" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:55.15-60.3|./74181.v:135.15-135.16|./mxalu_181.v:31.9-42.3" *)
  wire \inst_mxalu_181.inst_alu1.inst_s520.a ;
  (* hdlname = "inst_mxalu_181 inst_alu1 inst_s520 b" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:55.15-60.3|./74181.v:136.15-136.16|./mxalu_181.v:31.9-42.3" *)
  wire \inst_mxalu_181.inst_alu1.inst_s520.b ;
  (* hdlname = "inst_mxalu_181 inst_alu1 inst_s520 inst_s21 dt" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:55.15-60.3|./74181.v:120.15-120.17|./74181.v:138.15-141.3|./mxalu_181.v:31.9-42.3" *)
  (* unused_bits = "0 1 3" *)
  wire [4:0] \inst_mxalu_181.inst_alu1.inst_s520.inst_s21.dt ;
  (* hdlname = "inst_mxalu_181 inst_alu1 inst_s521 a" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:62.15-67.3|./74181.v:135.15-135.16|./mxalu_181.v:31.9-42.3" *)
  wire \inst_mxalu_181.inst_alu1.inst_s521.a ;
  (* hdlname = "inst_mxalu_181 inst_alu1 inst_s521 b" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:62.15-67.3|./74181.v:136.15-136.16|./mxalu_181.v:31.9-42.3" *)
  wire \inst_mxalu_181.inst_alu1.inst_s521.b ;
  (* hdlname = "inst_mxalu_181 inst_alu1 inst_s521 inst_s21 dt" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:62.15-67.3|./74181.v:120.15-120.17|./74181.v:138.15-141.3|./mxalu_181.v:31.9-42.3" *)
  (* unused_bits = "0 1 3" *)
  wire [4:0] \inst_mxalu_181.inst_alu1.inst_s521.inst_s21.dt ;
  (* hdlname = "inst_mxalu_181 inst_alu1 inst_s522 a" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:69.15-74.3|./74181.v:135.15-135.16|./mxalu_181.v:31.9-42.3" *)
  wire \inst_mxalu_181.inst_alu1.inst_s522.a ;
  (* hdlname = "inst_mxalu_181 inst_alu1 inst_s522 b" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:69.15-74.3|./74181.v:136.15-136.16|./mxalu_181.v:31.9-42.3" *)
  wire \inst_mxalu_181.inst_alu1.inst_s522.b ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [4:0] \inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [5:0] \inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT6_A_Q ;
  (* hdlname = "inst_mxalu_181 inst_alu1 inst_s522 inst_s21 dt" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:69.15-74.3|./74181.v:120.15-120.17|./74181.v:138.15-141.3|./mxalu_181.v:31.9-42.3" *)
  (* unused_bits = "0 1 3" *)
  wire [4:0] \inst_mxalu_181.inst_alu1.inst_s522.inst_s21.dt ;
  (* hdlname = "inst_mxalu_181 inst_alu1 inst_s523 a" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:76.15-81.3|./74181.v:135.15-135.16|./mxalu_181.v:31.9-42.3" *)
  wire \inst_mxalu_181.inst_alu1.inst_s523.a ;
  (* hdlname = "inst_mxalu_181 inst_alu1 inst_s523 b" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:76.15-81.3|./74181.v:136.15-136.16|./mxalu_181.v:31.9-42.3" *)
  wire \inst_mxalu_181.inst_alu1.inst_s523.b ;
  (* hdlname = "inst_mxalu_181 inst_alu1 inst_s523 inst_s21 dt" *)
  (* src = "./mxalu11u.v:51.12-63.3|./74181.v:76.15-81.3|./74181.v:120.15-120.17|./74181.v:138.15-141.3|./mxalu_181.v:31.9-42.3" *)
  (* unused_bits = "0 1 3" *)
  wire [4:0] \inst_mxalu_181.inst_alu1.inst_s523.inst_s21.dt ;
  (* hdlname = "inst_mxalu_181 inst_cgp go_n" *)
  (* src = "./mxalu11u.v:51.12-63.3|./fast_carry.v:28.14-28.18|./mxalu_181.v:44.13-51.3" *)
  wire \inst_mxalu_181.inst_cgp.go_n ;
  (* force_downto = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:7.19-7.20" *)
  wire [3:0] \inst_mxalu_181.inst_cgp.go_n_MISTRAL_ALUT4_Q_B ;
  (* hdlname = "inst_mxalu_181 inst_cgp po_n" *)
  (* src = "./mxalu11u.v:51.12-63.3|./fast_carry.v:28.20-28.24|./mxalu_181.v:44.13-51.3" *)
  wire \inst_mxalu_181.inst_cgp.po_n ;
  (* src = "./mxalu11u.v:34.15-34.21" *)
  input [3:0] opcode;
  wire [3:0] opcode;
  (* src = "./mxalu11u.v:29.15-29.16" *)
  output x;
  wire x;
  (* src = "./mxalu11u.v:30.15-30.16" *)
  output y;
  wire y;
  (* keep = 32'd1 *)
  MISTRAL_OB a_b_MISTRAL_OB_PAD (
    .I(\inst_mxalu_181.a_b ),
    .PAD(a_b)
  );
  (* keep = 32'd1 *)
  MISTRAL_OB cn4_n_MISTRAL_OB_PAD (
    .I(\inst_mxalu_181.cn4_n ),
    .PAD(cn4_n)
  );
  (* keep = 32'd1 *)
  MISTRAL_OB cn8_n_MISTRAL_OB_PAD (
    .I(\inst_mxalu_181.cn8_n ),
    .PAD(cn8_n)
  );
  (* keep = 32'd1 *)
  MISTRAL_OB f_MISTRAL_OB_PAD (
    .I(\inst_mxalu_181.f [7]),
    .PAD(f[7])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB f_MISTRAL_OB_PAD_1 (
    .I(\inst_mxalu_181.f [6]),
    .PAD(f[6])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB f_MISTRAL_OB_PAD_2 (
    .I(\inst_mxalu_181.f [5]),
    .PAD(f[5])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB f_MISTRAL_OB_PAD_3 (
    .I(\inst_mxalu_181.f [4]),
    .PAD(f[4])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB f_MISTRAL_OB_PAD_4 (
    .I(\inst_mxalu_181.f [3]),
    .PAD(f[3])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB f_MISTRAL_OB_PAD_5 (
    .I(\inst_mxalu_181.f [2]),
    .PAD(f[2])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB f_MISTRAL_OB_PAD_6 (
    .I(\inst_mxalu_181.f [1]),
    .PAD(f[1])
  );
  (* keep = 32'd1 *)
  MISTRAL_OB f_MISTRAL_OB_PAD_7 (
    .I(\inst_mxalu_181.f [0]),
    .PAD(f[0])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu181_rom.cs_n_MISTRAL_IB_O  (
    .O(\inst_mxalu181_rom.cs_n ),
    .PAD(cs_n)
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu181_rom.opcode_MISTRAL_IB_O  (
    .O(\inst_mxalu181_rom.opcode [3]),
    .PAD(opcode[3])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu181_rom.opcode_MISTRAL_IB_O_1  (
    .O(\inst_mxalu181_rom.opcode [2]),
    .PAD(opcode[2])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu181_rom.opcode_MISTRAL_IB_O_2  (
    .O(\inst_mxalu181_rom.opcode [1]),
    .PAD(opcode[1])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu181_rom.opcode_MISTRAL_IB_O_3  (
    .O(\inst_mxalu181_rom.opcode [0]),
    .PAD(opcode[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd1082130432)
  ) \inst_mxalu_181.a_b_MISTRAL_ALUT5_Q  (
    .A(\inst_mxalu_181.cn4_n_MISTRAL_ALUT6_F_Q [0]),
    .B(\inst_mxalu_181.f [5]),
    .C(\inst_mxalu_181.f [6]),
    .D(\inst_mxalu_181.cn4_n_MISTRAL_ALUT6_F_Q [1]),
    .E(\inst_mxalu_181.a_b_MISTRAL_ALUT5_Q_E [4]),
    .Q(\inst_mxalu_181.a_b )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'h8008000000000000)
  ) \inst_mxalu_181.a_b_MISTRAL_ALUT5_Q_E_MISTRAL_ALUT6_Q  (
    .A(\inst_mxalu_181.f [0]),
    .B(\inst_mxalu_181.f [1]),
    .C(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT4_A_Q [4]),
    .D(\inst_mxalu_181.f_MISTRAL_ALUT2_Q_1_B [1]),
    .E(\inst_mxalu_181.f [3]),
    .F(\inst_mxalu_181.f [4]),
    .Q(\inst_mxalu_181.a_b_MISTRAL_ALUT5_Q_E [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:35.36-37.10" *)
  MISTRAL_ALUT3 #(
    .LUT(8'h3b)
  ) \inst_mxalu_181.cn4_n_MISTRAL_ALUT3_Q  (
    .A(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [3]),
    .B(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [4]),
    .C(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [4]),
    .Q(\inst_mxalu_181.cn4_n )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'h55f755f555ff55f5)
  ) \inst_mxalu_181.cn4_n_MISTRAL_ALUT6_F  (
    .A(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [0]),
    .B(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C [1]),
    .C(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [0]),
    .D(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [1]),
    .E(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [4]),
    .F(\inst_mxalu_181.cn4_n ),
    .Q(\inst_mxalu_181.cn4_n_MISTRAL_ALUT6_F_Q [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:30.36-32.10" *)
  MISTRAL_ALUT2 #(
    .LUT(4'h1)
  ) \inst_mxalu_181.cn4_n_MISTRAL_ALUT6_F_Q_MISTRAL_ALUT2_Q  (
    .A(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [2]),
    .B(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [3]),
    .Q(\inst_mxalu_181.cn4_n_MISTRAL_ALUT6_F_Q [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:35.36-37.10" *)
  MISTRAL_ALUT3 #(
    .LUT(8'h8f)
  ) \inst_mxalu_181.cn8_n_MISTRAL_ALUT3_Q  (
    .A(\inst_mxalu_181.cn8_n_MISTRAL_ALUT3_Q_A [0]),
    .B(\inst_mxalu_181.cn4_n ),
    .C(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [5]),
    .Q(\inst_mxalu_181.cn8_n )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:35.36-37.10" *)
  MISTRAL_ALUT3 #(
    .LUT(8'h02)
  ) \inst_mxalu_181.cn8_n_MISTRAL_ALUT3_Q_A_MISTRAL_ALUT3_Q  (
    .A(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C [1]),
    .B(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [0]),
    .C(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [2]),
    .Q(\inst_mxalu_181.cn8_n_MISTRAL_ALUT3_Q_A [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:30.36-32.10" *)
  MISTRAL_ALUT2 #(
    .LUT(4'h6)
  ) \inst_mxalu_181.f_MISTRAL_ALUT2_Q  (
    .A(\inst_mxalu_181.cn4_n_MISTRAL_ALUT6_F_Q [0]),
    .B(\inst_mxalu_181.cn4_n_MISTRAL_ALUT6_F_Q [1]),
    .Q(\inst_mxalu_181.f [7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:30.36-32.10" *)
  MISTRAL_ALUT2 #(
    .LUT(4'h9)
  ) \inst_mxalu_181.f_MISTRAL_ALUT2_Q_1  (
    .A(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT4_A_Q [4]),
    .B(\inst_mxalu_181.f_MISTRAL_ALUT2_Q_1_B [1]),
    .Q(\inst_mxalu_181.f [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:30.36-32.10" *)
  MISTRAL_ALUT2 #(
    .LUT(4'h1)
  ) \inst_mxalu_181.f_MISTRAL_ALUT2_Q_1_B_MISTRAL_ALUT2_Q  (
    .A(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [4]),
    .B(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT4_A_Q [3]),
    .Q(\inst_mxalu_181.f_MISTRAL_ALUT2_Q_1_B [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'h9993)
  ) \inst_mxalu_181.f_MISTRAL_ALUT4_Q  (
    .A(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [0]),
    .B(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_B [1]),
    .C(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C [2]),
    .D(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [0]),
    .Q(\inst_mxalu_181.f [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd8751)
  ) \inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C  (
    .A(\inst_mxalu_181.inst_alu0.inst_s521.a ),
    .B(\inst_mxalu_181.inst_alu0.inst_s521.b_MISTRAL_ALUT5_A_Q [1]),
    .C(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C [2]),
    .D(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [0]),
    .E(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [1]),
    .Q(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'h2aaa)
  ) \inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q_MISTRAL_ALUT4_Q  (
    .A(\inst_mxalu181_rom.opcode [3]),
    .B(\inst_mxalu181_rom.opcode [2]),
    .C(\inst_mxalu181_rom.opcode [1]),
    .D(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'hfaff13f302f3143f)
  ) \inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT6_Q  (
    .A(\inst_mxalu_181.inst_alu0.inst_s520.b ),
    .B(\inst_mxalu181_rom.opcode [3]),
    .C(\inst_mxalu181_rom.opcode [2]),
    .D(\inst_mxalu_181.inst_alu0.inst_s520.a ),
    .E(\inst_mxalu181_rom.opcode [1]),
    .F(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd262506405)
  ) \inst_mxalu_181.f_MISTRAL_ALUT5_Q  (
    .A(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [0]),
    .B(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [3]),
    .C(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [2]),
    .D(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [4]),
    .E(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [4]),
    .Q(\inst_mxalu_181.f [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd2479657875)
  ) \inst_mxalu_181.f_MISTRAL_ALUT5_Q_1  (
    .A(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [0]),
    .B(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT4_A_Q [1]),
    .C(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [4]),
    .D(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT4_A_Q [3]),
    .E(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT4_A_Q [4]),
    .Q(\inst_mxalu_181.f [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'h9393999933939999)
  ) \inst_mxalu_181.f_MISTRAL_ALUT6_Q  (
    .A(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [0]),
    .B(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT6_A_Q [1]),
    .C(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C [1]),
    .D(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [4]),
    .E(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [4]),
    .F(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT6_A_Q [5]),
    .Q(\inst_mxalu_181.f [6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'h9399939993939399)
  ) \inst_mxalu_181.f_MISTRAL_ALUT6_Q_1  (
    .A(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [0]),
    .B(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_B [1]),
    .C(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_C [4]),
    .D(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_B [3]),
    .E(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [4]),
    .F(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT6_A_Q [5]),
    .Q(\inst_mxalu_181.f [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'h80c4)
  ) \inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_B_MISTRAL_ALUT4_Q  (
    .A(\inst_mxalu_181.inst_alu1.inst_s520.b ),
    .B(\inst_mxalu_181.inst_alu1.inst_s520.a ),
    .C(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [4]),
    .D(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [5]),
    .Q(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_B [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'hfae517f80a14d42b)
  ) \inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_B_MISTRAL_ALUT6_Q  (
    .A(\inst_mxalu_181.inst_alu1.inst_s521.b ),
    .B(\inst_mxalu181_rom.opcode [3]),
    .C(\inst_mxalu181_rom.opcode [2]),
    .D(\inst_mxalu_181.inst_alu1.inst_s521.a ),
    .E(\inst_mxalu181_rom.opcode [1]),
    .F(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_B [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'h091628c7352b27d8)
  ) \inst_mxalu_181.f_MISTRAL_ALUT6_Q_2  (
    .A(\inst_mxalu_181.inst_alu0.inst_s520.b ),
    .B(\inst_mxalu181_rom.opcode [3]),
    .C(\inst_mxalu181_rom.opcode [2]),
    .D(\inst_mxalu_181.inst_alu0.inst_s520.a ),
    .E(\inst_mxalu181_rom.opcode [1]),
    .F(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.f [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'h153fffff000f8acf)
  ) \inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q  (
    .A(\inst_mxalu_181.inst_alu1.inst_s520.b ),
    .B(\inst_mxalu_181.inst_alu1.inst_s521.b ),
    .C(\inst_mxalu_181.inst_alu1.inst_s521.a ),
    .D(\inst_mxalu_181.inst_alu1.inst_s520.a ),
    .E(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [4]),
    .F(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [5]),
    .Q(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'h0ec7)
  ) \inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E_MISTRAL_ALUT4_Q  (
    .A(\inst_mxalu181_rom.opcode [3]),
    .B(\inst_mxalu181_rom.opcode [2]),
    .C(\inst_mxalu181_rom.opcode [1]),
    .D(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'hc70e)
  ) \inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E_MISTRAL_ALUT4_Q_1  (
    .A(\inst_mxalu181_rom.opcode [3]),
    .B(\inst_mxalu181_rom.opcode [2]),
    .C(\inst_mxalu181_rom.opcode [1]),
    .D(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [5])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu_181.inst_alu0.inst_s520.a_MISTRAL_IB_O  (
    .O(\inst_mxalu_181.inst_alu0.inst_s520.a ),
    .PAD(a[0])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu_181.inst_alu0.inst_s520.b_MISTRAL_IB_O  (
    .O(\inst_mxalu_181.inst_alu0.inst_s520.b ),
    .PAD(b[0])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu_181.inst_alu0.inst_s521.a_MISTRAL_IB_O  (
    .O(\inst_mxalu_181.inst_alu0.inst_s521.a ),
    .PAD(a[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd4195814100)
  ) \inst_mxalu_181.inst_alu0.inst_s521.b_MISTRAL_ALUT5_A  (
    .A(\inst_mxalu_181.inst_alu0.inst_s521.b ),
    .B(\inst_mxalu181_rom.opcode [3]),
    .C(\inst_mxalu181_rom.opcode [2]),
    .D(\inst_mxalu181_rom.opcode [1]),
    .E(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.inst_alu0.inst_s521.b_MISTRAL_ALUT5_A_Q [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'hfea51f7801a4d24b)
  ) \inst_mxalu_181.inst_alu0.inst_s521.b_MISTRAL_ALUT6_A  (
    .A(\inst_mxalu_181.inst_alu0.inst_s521.b ),
    .B(\inst_mxalu181_rom.opcode [3]),
    .C(\inst_mxalu_181.inst_alu0.inst_s521.a ),
    .D(\inst_mxalu181_rom.opcode [2]),
    .E(\inst_mxalu181_rom.opcode [1]),
    .F(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_B [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'h010a00070e0b0d04)
  ) \inst_mxalu_181.inst_alu0.inst_s521.b_MISTRAL_ALUT6_A_1  (
    .A(\inst_mxalu_181.inst_alu0.inst_s521.b ),
    .B(\inst_mxalu181_rom.opcode [3]),
    .C(\inst_mxalu_181.inst_alu0.inst_s521.a ),
    .D(\inst_mxalu181_rom.opcode [2]),
    .E(\inst_mxalu181_rom.opcode [1]),
    .F(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [1])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu_181.inst_alu0.inst_s521.b_MISTRAL_IB_O  (
    .O(\inst_mxalu_181.inst_alu0.inst_s521.b ),
    .PAD(b[1])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu_181.inst_alu0.inst_s522.a_MISTRAL_IB_O  (
    .O(\inst_mxalu_181.inst_alu0.inst_s522.a ),
    .PAD(a[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'h80c4)
  ) \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT4_A  (
    .A(\inst_mxalu_181.inst_alu0.inst_s522.b ),
    .B(\inst_mxalu_181.inst_alu0.inst_s522.a ),
    .C(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [4]),
    .D(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [5]),
    .Q(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT4_A_Q [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'hccccccccc4c4c400)
  ) \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT4_A_Q_MISTRAL_ALUT6_Q  (
    .A(\inst_mxalu_181.inst_alu0.inst_s521.a ),
    .B(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [0]),
    .C(\inst_mxalu_181.inst_alu0.inst_s521.b_MISTRAL_ALUT5_A_Q [1]),
    .D(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C [2]),
    .E(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [0]),
    .F(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [1]),
    .Q(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT4_A_Q [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'hfae517f80a14d42b)
  ) \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT4_A_Q_MISTRAL_ALUT6_Q_1  (
    .A(\inst_mxalu_181.inst_alu0.inst_s523.b ),
    .B(\inst_mxalu181_rom.opcode [3]),
    .C(\inst_mxalu181_rom.opcode [2]),
    .D(\inst_mxalu_181.inst_alu0.inst_s523.a ),
    .E(\inst_mxalu181_rom.opcode [1]),
    .F(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT4_A_Q [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'h001a000700eb00d4)
  ) \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A  (
    .A(\inst_mxalu_181.inst_alu0.inst_s522.b ),
    .B(\inst_mxalu181_rom.opcode [3]),
    .C(\inst_mxalu181_rom.opcode [2]),
    .D(\inst_mxalu_181.inst_alu0.inst_s522.a ),
    .E(\inst_mxalu181_rom.opcode [1]),
    .F(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'h31f8)
  ) \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q_MISTRAL_ALUT4_Q  (
    .A(\inst_mxalu181_rom.opcode [3]),
    .B(\inst_mxalu181_rom.opcode [2]),
    .C(\inst_mxalu181_rom.opcode [1]),
    .D(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'h439e)
  ) \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q_MISTRAL_ALUT4_Q_1  (
    .A(\inst_mxalu181_rom.opcode [3]),
    .B(\inst_mxalu181_rom.opcode [2]),
    .C(\inst_mxalu181_rom.opcode [1]),
    .D(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'h0500e800f5002b00)
  ) \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q_MISTRAL_ALUT6_Q  (
    .A(\inst_mxalu_181.inst_alu0.inst_s523.b ),
    .B(\inst_mxalu181_rom.opcode [3]),
    .C(\inst_mxalu181_rom.opcode [2]),
    .D(\inst_mxalu_181.inst_alu0.inst_s523.a ),
    .E(\inst_mxalu181_rom.opcode [1]),
    .F(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'h135fffff000f8caf)
  ) \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B  (
    .A(\inst_mxalu_181.inst_alu0.inst_s523.b ),
    .B(\inst_mxalu_181.inst_alu0.inst_s522.b ),
    .C(\inst_mxalu_181.inst_alu0.inst_s523.a ),
    .D(\inst_mxalu_181.inst_alu0.inst_s522.a ),
    .E(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [4]),
    .F(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [5]),
    .Q(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:30.36-32.10" *)
  MISTRAL_ALUT2 #(
    .LUT(4'h2)
  ) \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q_MISTRAL_ALUT2_Q  (
    .A(\inst_mxalu_181.inst_alu0.inst_s521.a ),
    .B(\inst_mxalu_181.inst_alu0.inst_s521.b_MISTRAL_ALUT5_A_Q [1]),
    .Q(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd15925490)
  ) \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q_MISTRAL_ALUT5_Q  (
    .A(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [0]),
    .B(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [1]),
    .C(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [2]),
    .D(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [3]),
    .E(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [4]),
    .Q(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'h001a000700eb00d4)
  ) \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q_MISTRAL_ALUT6_Q  (
    .A(\inst_mxalu_181.inst_alu0.inst_s520.b ),
    .B(\inst_mxalu181_rom.opcode [3]),
    .C(\inst_mxalu181_rom.opcode [2]),
    .D(\inst_mxalu_181.inst_alu0.inst_s520.a ),
    .E(\inst_mxalu181_rom.opcode [1]),
    .F(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'hcedfcedf0000cedf)
  ) \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q_MISTRAL_ALUT6_Q_1  (
    .A(\inst_mxalu_181.inst_alu0.inst_s523.b ),
    .B(\inst_mxalu_181.inst_alu0.inst_s523.a ),
    .C(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [2]),
    .D(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [3]),
    .E(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [4]),
    .F(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [5]),
    .Q(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [4])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_IB_O  (
    .O(\inst_mxalu_181.inst_alu0.inst_s522.b ),
    .PAD(b[2])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu_181.inst_alu0.inst_s523.a_MISTRAL_IB_O  (
    .O(\inst_mxalu_181.inst_alu0.inst_s523.a ),
    .PAD(a[3])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu_181.inst_alu0.inst_s523.b_MISTRAL_IB_O  (
    .O(\inst_mxalu_181.inst_alu0.inst_s523.b ),
    .PAD(b[3])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu_181.inst_alu1.inst_s520.a_MISTRAL_IB_O  (
    .O(\inst_mxalu_181.inst_alu1.inst_s520.a ),
    .PAD(a[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd32571)
  ) \inst_mxalu_181.inst_alu1.inst_s520.b_MISTRAL_ALUT5_A  (
    .A(\inst_mxalu_181.inst_alu1.inst_s520.b ),
    .B(\inst_mxalu_181.inst_alu1.inst_s520.a ),
    .C(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [4]),
    .D(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [5]),
    .E(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_C [4]),
    .Q(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'h001a000700eb00d4)
  ) \inst_mxalu_181.inst_alu1.inst_s520.b_MISTRAL_ALUT6_A  (
    .A(\inst_mxalu_181.inst_alu1.inst_s520.b ),
    .B(\inst_mxalu181_rom.opcode [3]),
    .C(\inst_mxalu181_rom.opcode [2]),
    .D(\inst_mxalu_181.inst_alu1.inst_s520.a ),
    .E(\inst_mxalu181_rom.opcode [1]),
    .F(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_C [4])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu_181.inst_alu1.inst_s520.b_MISTRAL_IB_O  (
    .O(\inst_mxalu_181.inst_alu1.inst_s520.b ),
    .PAD(b[4])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu_181.inst_alu1.inst_s521.a_MISTRAL_IB_O  (
    .O(\inst_mxalu_181.inst_alu1.inst_s521.a ),
    .PAD(a[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'h80c4)
  ) \inst_mxalu_181.inst_alu1.inst_s521.b_MISTRAL_ALUT4_A  (
    .A(\inst_mxalu_181.inst_alu1.inst_s521.b ),
    .B(\inst_mxalu_181.inst_alu1.inst_s521.a ),
    .C(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [4]),
    .D(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [5]),
    .Q(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_C [5])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu_181.inst_alu1.inst_s521.b_MISTRAL_IB_O  (
    .O(\inst_mxalu_181.inst_alu1.inst_s521.b ),
    .PAD(b[5])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu_181.inst_alu1.inst_s522.a_MISTRAL_IB_O  (
    .O(\inst_mxalu_181.inst_alu1.inst_s522.a ),
    .PAD(a[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'h80c4)
  ) \inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A  (
    .A(\inst_mxalu_181.inst_alu1.inst_s522.b ),
    .B(\inst_mxalu_181.inst_alu1.inst_s522.a ),
    .C(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [4]),
    .D(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [5]),
    .Q(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'h3120)
  ) \inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_1  (
    .A(\inst_mxalu_181.inst_alu1.inst_s522.b ),
    .B(\inst_mxalu_181.inst_alu1.inst_s522.a ),
    .C(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [2]),
    .D(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [3]),
    .Q(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'hcedfcedf0000cedf)
  ) \inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q_MISTRAL_ALUT6_Q  (
    .A(\inst_mxalu_181.inst_alu1.inst_s521.b ),
    .B(\inst_mxalu_181.inst_alu1.inst_s521.a ),
    .C(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [2]),
    .D(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [3]),
    .E(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_C [4]),
    .F(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_C [5]),
    .Q(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'hfea51f7801a4d24b)
  ) \inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT6_A  (
    .A(\inst_mxalu_181.inst_alu1.inst_s522.b ),
    .B(\inst_mxalu181_rom.opcode [3]),
    .C(\inst_mxalu_181.inst_alu1.inst_s522.a ),
    .D(\inst_mxalu181_rom.opcode [2]),
    .E(\inst_mxalu181_rom.opcode [1]),
    .F(\inst_mxalu181_rom.opcode [0]),
    .Q(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT6_A_Q [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:30.36-32.10" *)
  MISTRAL_ALUT2 #(
    .LUT(4'h2)
  ) \inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT6_A_Q_MISTRAL_ALUT2_Q  (
    .A(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [3]),
    .B(\inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [4]),
    .Q(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT6_A_Q [5])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_IB_O  (
    .O(\inst_mxalu_181.inst_alu1.inst_s522.b ),
    .PAD(b[6])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu_181.inst_alu1.inst_s523.a_MISTRAL_IB_O  (
    .O(\inst_mxalu_181.inst_alu1.inst_s523.a ),
    .PAD(a[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'h3120)
  ) \inst_mxalu_181.inst_alu1.inst_s523.b_MISTRAL_ALUT4_A  (
    .A(\inst_mxalu_181.inst_alu1.inst_s523.b ),
    .B(\inst_mxalu_181.inst_alu1.inst_s523.a ),
    .C(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [2]),
    .D(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [3]),
    .Q(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'h80c4)
  ) \inst_mxalu_181.inst_alu1.inst_s523.b_MISTRAL_ALUT4_A_1  (
    .A(\inst_mxalu_181.inst_alu1.inst_s523.b ),
    .B(\inst_mxalu_181.inst_alu1.inst_s523.a ),
    .C(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [4]),
    .D(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [5]),
    .Q(\inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [2])
  );
  (* keep = 32'd1 *)
  MISTRAL_IB \inst_mxalu_181.inst_alu1.inst_s523.b_MISTRAL_IB_O  (
    .O(\inst_mxalu_181.inst_alu1.inst_s523.b ),
    .PAD(b[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:40.36-42.10" *)
  MISTRAL_ALUT4 #(
    .LUT(16'h0f07)
  ) \inst_mxalu_181.inst_cgp.go_n_MISTRAL_ALUT4_Q  (
    .A(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [3]),
    .B(\inst_mxalu_181.inst_cgp.go_n_MISTRAL_ALUT4_Q_B [1]),
    .C(\inst_mxalu_181.cn8_n_MISTRAL_ALUT3_Q_A [0]),
    .D(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [5]),
    .Q(\inst_mxalu_181.inst_cgp.go_n )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:45.36-47.10" *)
  MISTRAL_ALUT5 #(
    .LUT(32'd32571)
  ) \inst_mxalu_181.inst_cgp.go_n_MISTRAL_ALUT4_Q_B_MISTRAL_ALUT5_Q  (
    .A(\inst_mxalu_181.inst_alu0.inst_s520.b ),
    .B(\inst_mxalu_181.inst_alu0.inst_s520.a ),
    .C(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [4]),
    .D(\inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [5]),
    .E(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [2]),
    .Q(\inst_mxalu_181.inst_cgp.go_n_MISTRAL_ALUT4_Q_B [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/usr/bin/../share/yosys/intel_alm/common/alm_map.v:50.36-52.10" *)
  MISTRAL_ALUT6 #(
    .LUT(64'hffffffff31ff0000)
  ) \inst_mxalu_181.inst_cgp.po_n_MISTRAL_ALUT6_Q  (
    .A(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [0]),
    .B(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [1]),
    .C(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [2]),
    .D(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [3]),
    .E(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [4]),
    .F(\inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [5]),
    .Q(\inst_mxalu_181.inst_cgp.po_n )
  );
  (* keep = 32'd1 *)
  MISTRAL_OB x_MISTRAL_OB_PAD (
    .I(\inst_mxalu_181.inst_cgp.go_n ),
    .PAD(x)
  );
  (* keep = 32'd1 *)
  MISTRAL_OB y_MISTRAL_OB_PAD (
    .I(\inst_mxalu_181.inst_cgp.po_n ),
    .PAD(y)
  );
  assign \inst_mxalu_181.f_MISTRAL_ALUT6_Q_C_MISTRAL_ALUT6_Q_E [3:0] = { \inst_mxalu_181.inst_alu0.inst_s522.a , \inst_mxalu_181.inst_alu0.inst_s523.a , \inst_mxalu_181.inst_alu0.inst_s522.b , \inst_mxalu_181.inst_alu0.inst_s523.b  };
  assign { \inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [3], \inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [1] } = \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [4:3];
  assign \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [1:0] = { \inst_mxalu_181.inst_alu0.inst_s523.a , \inst_mxalu_181.inst_alu0.inst_s523.b  };
  assign \inst_mxalu_181.inst_alu0.inst_s521.b_MISTRAL_ALUT5_A_Q [0] = \inst_mxalu_181.inst_alu0.inst_s521.a ;
  assign \inst_mxalu_181.f_MISTRAL_ALUT2_Q_1_B [0] = \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT4_A_Q [4];
  assign \inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_C [3:0] = { \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [3:2], \inst_mxalu_181.inst_alu1.inst_s521.a , \inst_mxalu_181.inst_alu1.inst_s521.b  };
  assign { \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT4_A_Q [2], \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT4_A_Q [0] } = { \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_A_Q [4], \inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [0] };
  assign { \inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT6_A_Q [4:2], \inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT6_A_Q [0] } = { \inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [4], \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [4], \inst_mxalu_181.f_MISTRAL_ALUT6_Q_C [1], \inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [0] };
  assign \inst_mxalu_181.a_b_MISTRAL_ALUT5_Q_E [3:0] = { \inst_mxalu_181.cn4_n_MISTRAL_ALUT6_F_Q [1], \inst_mxalu_181.f [6:5], \inst_mxalu_181.cn4_n_MISTRAL_ALUT6_F_Q [0] };
  assign { \inst_mxalu_181.f_MISTRAL_ALUT6_Q_C [5:2], \inst_mxalu_181.f_MISTRAL_ALUT6_Q_C [0] } = { \inst_mxalu_181.cn4_n , \inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [4], \inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT4_A_Q [1:0], \inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [0] };
  assign { \inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_B [5:4], \inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_B [2], \inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_B [0] } = { \inst_mxalu_181.inst_alu1.inst_s522.b_MISTRAL_ALUT6_A_Q [5], \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [4], \inst_mxalu_181.f_MISTRAL_ALUT6_Q_1_C [4], \inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [0] };
  assign { \inst_mxalu_181.f_MISTRAL_ALUT4_Q_C [4:3], \inst_mxalu_181.f_MISTRAL_ALUT4_Q_C [1:0] } = { \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [1:0], \inst_mxalu_181.inst_alu0.inst_s521.b_MISTRAL_ALUT5_A_Q [1], \inst_mxalu_181.inst_alu0.inst_s521.a  };
  assign { \inst_mxalu_181.inst_cgp.go_n_MISTRAL_ALUT4_Q_B [3:2], \inst_mxalu_181.inst_cgp.go_n_MISTRAL_ALUT4_Q_B [0] } = { \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [5], \inst_mxalu_181.cn8_n_MISTRAL_ALUT3_Q_A [0], \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [3] };
  assign { \inst_mxalu_181.f_MISTRAL_ALUT4_Q_B [3:2], \inst_mxalu_181.f_MISTRAL_ALUT4_Q_B [0] } = { \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [0], \inst_mxalu_181.f_MISTRAL_ALUT4_Q_C [2], \inst_mxalu_181.f_MISTRAL_ALUT4_Q_C_MISTRAL_ALUT5_C_Q [0] };
  assign \inst_mxalu_181.cn8_n_MISTRAL_ALUT3_Q_A [2:1] = { \inst_mxalu_181.inst_alu0.inst_s522.b_MISTRAL_ALUT6_B_Q [5], \inst_mxalu_181.cn4_n  };
  assign { \inst_mxalu_181.inst_alu0.inst_s520.inst_s21.dt [4], \inst_mxalu_181.inst_alu0.inst_s520.inst_s21.dt [2] } = { \inst_mxalu_181.inst_alu0.inst_s520.b , \inst_mxalu_181.inst_alu0.inst_s520.a  };
  assign { \inst_mxalu_181.inst_alu0.inst_s521.inst_s21.dt [4], \inst_mxalu_181.inst_alu0.inst_s521.inst_s21.dt [2] } = { \inst_mxalu_181.inst_alu0.inst_s521.b , \inst_mxalu_181.inst_alu0.inst_s521.a  };
  assign { \inst_mxalu_181.inst_alu0.inst_s522.inst_s21.dt [4], \inst_mxalu_181.inst_alu0.inst_s522.inst_s21.dt [2] } = { \inst_mxalu_181.inst_alu0.inst_s522.b , \inst_mxalu_181.inst_alu0.inst_s522.a  };
  assign { \inst_mxalu_181.inst_alu0.inst_s523.inst_s21.dt [4], \inst_mxalu_181.inst_alu0.inst_s523.inst_s21.dt [2] } = { \inst_mxalu_181.inst_alu0.inst_s523.b , \inst_mxalu_181.inst_alu0.inst_s523.a  };
  assign { \inst_mxalu_181.inst_alu1.inst_s520.inst_s21.dt [4], \inst_mxalu_181.inst_alu1.inst_s520.inst_s21.dt [2] } = { \inst_mxalu_181.inst_alu1.inst_s520.b , \inst_mxalu_181.inst_alu1.inst_s520.a  };
  assign { \inst_mxalu_181.inst_alu1.inst_s521.inst_s21.dt [4], \inst_mxalu_181.inst_alu1.inst_s521.inst_s21.dt [2] } = { \inst_mxalu_181.inst_alu1.inst_s521.b , \inst_mxalu_181.inst_alu1.inst_s521.a  };
  assign { \inst_mxalu_181.inst_alu1.inst_s522.inst_s21.dt [4], \inst_mxalu_181.inst_alu1.inst_s522.inst_s21.dt [2] } = { \inst_mxalu_181.inst_alu1.inst_s522.b , \inst_mxalu_181.inst_alu1.inst_s522.a  };
  assign { \inst_mxalu_181.inst_alu1.inst_s523.inst_s21.dt [4], \inst_mxalu_181.inst_alu1.inst_s523.inst_s21.dt [2] } = { \inst_mxalu_181.inst_alu1.inst_s523.b , \inst_mxalu_181.inst_alu1.inst_s523.a  };

`ifdef WAVE
  initial begin
    $dumpfile("mxalu11u_intel.vcd");
    $dumpvars(0, mxalu11u_intel);
  end
`endif

endmodule
